#define T_SYMBOL                          1
#define T_VARIABLE                        2
#define T_EXPORT                          3
#define T_OP_ASSIGN                       4
#define T_STRING                          5
#define T_OP_PREDOT                       6
#define T_OP_POSTDOT                      7
#define T_OP_IMMEDIATE                    8
#define T_OP_COND                         9
#define T_OP_PREPEND                     10
#define T_OP_APPEND                      11
#define T_TSYMBOL                        12
#define T_BEFORE                         13
#define T_AFTER                          14
#define T_ADDTASK                        15
#define T_ADDHANDLER                     16
#define T_FSYMBOL                        17
#define T_EXPORT_FUNC                    18
#define T_ISYMBOL                        19
#define T_INHERIT                        20
#define T_INCLUDE                        21
#define T_REQUIRE                        22
#define T_PROC_BODY                      23
#define T_PROC_OPEN                      24
#define T_PROC_CLOSE                     25
#define T_PYTHON                         26
#define T_FAKEROOT                       27
#define T_DEF_BODY                       28
#define T_DEF_ARGS                       29
