#define T_SYMBOL                          1
#define T_VARIABLE                        2
#define T_EXPORT                          3
#define T_OP_ASSIGN                       4
#define T_STRING                          5
#define T_OP_IMMEDIATE                    6
#define T_OP_COND                         7
#define T_OP_PREPEND                      8
#define T_OP_APPEND                       9
#define T_TSYMBOL                        10
#define T_BEFORE                         11
#define T_AFTER                          12
#define T_ADDTASK                        13
#define T_ADDHANDLER                     14
#define T_FSYMBOL                        15
#define T_EXPORT_FUNC                    16
#define T_ISYMBOL                        17
#define T_INHERIT                        18
#define T_INCLUDE                        19
#define T_REQUIRE                        20
#define T_PROC_BODY                      21
#define T_PROC_OPEN                      22
#define T_PROC_CLOSE                     23
#define T_PYTHON                         24
#define T_FAKEROOT                       25
#define T_DEF_BODY                       26
#define T_DEF_ARGS                       27
